### ISSUE TITLE
Get the Production Master Server DDOS on the Service itself or on the System?

### ISSUE THREAD

**Issue by daBONDi** [realitymod/PRMasterServer#3]
If the DDOS is going on the Service itself we could make an in Memory Cache of IP Adresses

When IP Address got More then 1 Request in a Second then the Server not Starting a TCP Session for like 5 mins?

**Comment by art567** [comment]
@daBONDi good suggestion! I have similar opinion about saveable server lists: it should be saved in database instantly, and then we could switch only activation flag if server online, and deactivate it if this server goes offline. This is fastest and safe, and whole server IP array could be transferred directly from database.

**Comment by daBONDi** [comment]
What type of dos attack happend? Directly on the MasterServer Service itself? or on the OS?
Is there any posibliy to talkl on irc or something else :-)

Maybe it was the cdkey service because its udp and you use only 1 single thread, so they could fuck it up with simple udp messages

Want only to help :-) my lovly game

**Comment by daBONDi** [comment]
Got some idea to get rid of a spamming udp client

https://social.msdn.microsoft.com/Forums/vstudio/en-US/f6580aaf-ed47-4bb1-b976-6108595b8dfb/block-ip-in-windows-through-c?forum=csharpgeneral

We could block client ip for a timeframe if he requests more cdkey checks then x time a minute

Will try it out and make a test client

**Comment by AncientMan2002** [comment]
The DDOS attacks are against the server in general, it's not against the ports used by the master server. So it's not at all because the CD Key service uses UDP or that it uses one thread (which btw, is exactly the correct way, spawning hundreds of threads for each connection is extremely bad).

While sure, putting in IP bans could be useful for other reasons, it's not at all useful for the current attack. By the time a high amount of network traffic hits the master server service, the damage is done. DDOS attacks need to be handled upstream by the provider.

Don't worry, it'll be sorted on the weekend when I get some time to switch providers :)

**Comment by art567** [comment]
@AncientMan2002 In case of powerful attacks against central master server, the idea of having that single point of failure would be not good idea. For players all around world current situation feeling so bad.

Possibly distributed / p2p solutions and some of it's variants will help. What if we integrate PRMasterServer into PRLauncher and then link game binaries to PRLauncher (localhost)?

Imo we can give that gamespy stuff directly to clients, move authentication system into web backend and handle all serverlists (json and serialized data) right there. Web could be easily managed and provides more failover/caching options.

**Comment by daBONDi** [comment]
Don't think we could do that because the Server is sending the Request also to the Master Server for the fake cdkey check(iam right here @AncientMan2002 ?), and dont know if PR Team got Source Code for the Server Binary, Maybe @AncientMan2002  can give us some detail about that

@art567 When they got the sourcecode they would removed it already i think.

i nearly finished my Load Testing Application for CDKey Service in PRMasterserver.

https://github.com/daBONDi/PRMasterserverClientEmulator

nothing Special, laugh @Me

**Comment by art567** [comment]
@daBONDi GameServers requires only hbmaster3 service to check if gamespy backend is available to normal operation, then sends initial and periodic heartbeat packets. It's required to announce this server in master server list. keymaster service is not required at all.

This is my explanation based on real observations, experiments and work.

Refer to official documentation
[Network_Ports_Used_by_GameSpy_Services_-_Powered_by_GameSpy_Wiki.pdf](https://github.com/realitymod/PRMasterServer/files/118783/Network_Ports_Used_by_GameSpy_Services_-_Powered_by_GameSpy_Wiki.pdf)

And source code of stock GameSpy SDK
https://github.com/art567/GameSpy

**Comment by daBONDi** [comment]
@art567 
My Observation on the CDKey Check is from descriped on aluigi http://aluigi.altervista.org/papers/gskey-auth.txt

GameServer is checking for GameClient into the Masterserver if the Client has a Valid Key, See Part 4
Or is this Doc Invalid? i'm quite new to the gamespy stuff :-)

@art567 Good Idea to with the HTTP Stuff
I think it would be possible to make this MasterServer like an HTTP API Client and Pointing the Client and the Server to localhost, and then Communicate over an HTTP API(JSON-RPC?) to a Central Distributed Backend Service, so the Communication is on the HTTP Protocol and it would benifit from it (Loadbalancing and so on). What you think @AncientMan2002?

**Comment by AncientMan2002** [comment]
TBH, I'd rather just stick with the current system, which has worked almost flawlessly for the last 2 years, until of course 1 week ago.

Sure, it's a single point of failure, and I completely agree it's less than ideal. But I want to see how a new host handles things first (will be sorting this out tomorrow). If it all proves ineffective, then we can consider some changes to how everything works.

But yeah, a localhost MS built into PRLauncher, communicating with a cloud based HTTPS service is probably a decent decentralised approach. Would also solve some issues with logins and CTD's when the MS goes down. CD Keys could be handled on the game server relatively easily by a server side launcher. However, while that all sounds well and good, it's quite a lot of work, and as I mentioned before, I don't want to go down this path unless there's no other choice.

Lets come back to this in a few days?

**Comment by daBONDi** [comment]
@AncientMan2002 Yeah, i agree, we should first get the current System running, we cannot do this stuff overnight, and need some carfully api planning.

**Comment by SINE** [comment]
@AncientMan2002 FirstColo GmbH in Germany is specialist against DDoS toward dedicated servers, they have one of the best protection plans available regarding industry standard. You should consider using a VPS that is hosted in one of their systems or protected by their shield, should be affordable, if you're not planning to rent a huge machine for the most critical parts.

**Comment by daBONDi** [comment]
@AncientMan2002 still DDos ? possible to get a sniff for diag?
